-- Creating Table

CREATE TABLE CRIME_DETAILS (
	ID INT, 
	STATE VARCHAR(50), 
    YEAR INT,
    RAPE INT, 
    KIDNAP_ASSAULT INT, 
    DOWRY_DEATHS INT, 
    ASSUALT_AGAINST_WOMEN INT, 
    ASSAULT_AGAINST_MODESTY_OF_WOMEN INT, 
    DOMESTIC_VIOLENCE INT, 
    WOMEN_TRAFFICKING INT  
);
/*
What is the total number of crimes reported for each type of crime across all states?
List all the states where the total number of crimes exceeded 10,000 in any given year.
How many crimes were reported in each year across all states?
Find the total number of crimes reported in Delhi over the 20-year period.
Top 5 states which had the lowest number of reported crimes in 2020?
*/


SELECT *
FROM CRIME_DETAILS;


-- 1. What is the total number of crimes reported for each type of crime across all states?
SELECT 
	STATE, 
    SUM(RAPE) AS TOTAL_RAPES,
    SUM(KIDNAP_ASSAULT) AS TOTAL_KIDNAP_ASSAULT,
    SUM(DOWRY_DEATHS) AS TOTAL_DOWRY_DEATHS, 
    SUM(ASSAULT_AGAINST_WOMEN) AS TOTAL_ASSAULTS, 
    SUM(ASSAULT_AGAINST_MODESTY_OF_WOMEN) AS TOTAL_ASSAULTS_MODESTY, 
    SUM(DOMESTIC_VIOLENCE) AS TOTAL_DOMESTIC_VIOELENCE, 
    SUM(WOMEN_TRAFFICKING) AS TOTAL_TRAFFICKING
FROM CRIME_DETAILS
GROUP BY 1
ORDER BY 1;


-- 2. List all the states where the total number of crimes exceeded 10,000 in any given year.
WITH STATE_WISE_CRIME AS (
	SELECT 
		STATE,
        YEAR,
		SUM(RAPE) + SUM(KIDNAP_ASSAULT) + SUM(DOWRY_DEATHS) + SUM(ASSAULT_AGAINST_WOMEN) + 
		SUM(ASSAULT_AGAINST_MODESTY_OF_WOMEN) + SUM(DOMESTIC_VIOLENCE) + SUM(WOMEN_TRAFFICKING) 
		AS TOTAL_CRIMES
	FROM CRIME_DETAILS
	GROUP BY 1,2
)
SELECT 
	STATE, 
    YEAR,
    TOTAL_CRIMES
FROM STATE_WISE_CRIME
WHERE TOTAL_CRIMES > 10000
ORDER BY 3 DESC;


-- 3. How many crimes were reported in each year across all states?
SELECT 
		STATE,
        YEAR,
		SUM(RAPE) + SUM(KIDNAP_ASSAULT) + SUM(DOWRY_DEATHS) + SUM(ASSAULT_AGAINST_WOMEN) + 
		SUM(ASSAULT_AGAINST_MODESTY_OF_WOMEN) + SUM(DOMESTIC_VIOLENCE) + SUM(WOMEN_TRAFFICKING) 
		AS TOTAL_CRIMES
FROM CRIME_DETAILS
GROUP BY 1,2;


-- 4. Find the total number of crimes reported in Delhi over the 20-year period.
SELECT 
		STATE,
        YEAR, 
		SUM(RAPE) + SUM(KIDNAP_ASSAULT) + SUM(DOWRY_DEATHS) + SUM(ASSAULT_AGAINST_WOMEN) + 
		SUM(ASSAULT_AGAINST_MODESTY_OF_WOMEN) + SUM(DOMESTIC_VIOLENCE) + SUM(WOMEN_TRAFFICKING) 
		AS TOTAL_CRIMES
FROM CRIME_DETAILS
WHERE STATE = 'Delhi UT'
GROUP BY 1,2;


-- 5. Top 5 states which had the lowest number of reported crimes in 2020?
SELECT 
		STATE,
        YEAR, 
		SUM(RAPE) + SUM(KIDNAP_ASSAULT) + SUM(DOWRY_DEATHS) + SUM(ASSAULT_AGAINST_WOMEN) + 
		SUM(ASSAULT_AGAINST_MODESTY_OF_WOMEN) + SUM(DOMESTIC_VIOLENCE) + SUM(WOMEN_TRAFFICKING) 
		AS TOTAL_CRIMES
FROM CRIME_DETAILS
WHERE YEAR = 2020
GROUP BY 1
ORDER BY 3 ASC
LIMIT 5;


-- 6. Difference between total number of crimes between the year 2019 and 2020
WITH TOTAL_CRIMES AS (
	SELECT 
		STATE, 
		YEAR,
		SUM(RAPE) + SUM(KIDNAP_ASSAULT) + SUM(DOWRY_DEATHS) + SUM(ASSAULT_AGAINST_WOMEN) +
		SUM(ASSAULT_AGAINST_MODESTY_OF_WOMEN) + SUM(DOMESTIC_VIOLENCE) + SUM(WOMEN_TRAFFICKING) AS TOTAL_CRIMES
	FROM CRIME_DETAILS
	WHERE YEAR BETWEEN 2019 AND 2020
	GROUP BY 1,2
)
SELECT *, 
	LAG(TOTAL_CRIMES, 1, 0) OVER(PARTITION BY STATE ORDER BY YEAR) AS PREVIOUS_YEAR_CRIMES, 
    TOTAL_CRIMES - LAG(TOTAL_CRIMES, 1, 0) OVER(PARTITION BY STATE ORDER BY YEAR) AS CRIME_DECREASE
FROM TOTAL_CRIMES;











